"""geolocation migration

Revision ID: e0d01e1211da
Revises: e56c093e3b42
Create Date: 2026-02-15 13:11:25.925983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d01e1211da'
down_revision: Union[str, Sequence[str], None] = 'e56c093e3b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create geolocations table
    op.create_table(
        'geolocations',
        sa.Column('id', sa.UUID(as_uuid=True), nullable=False),
        sa.Column('continent', sa.String(length=2), nullable=False),
        sa.Column('continent_name', sa.String(length=100), nullable=False),
        sa.Column('places_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('country_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('continent') # reinforce index generated by model.
    )
    
    # Use update trigger for updated_at
    op.execute("""
        CREATE TRIGGER update_geolocations_updated_at 
        BEFORE UPDATE ON geolocations
        FOR EACH ROW
        EXECUTE FUNCTION update_updated_at_column();
    """)
    

def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS update_geolocations_updated_at ON geolocations")
    op.drop_table('geolocations')
