name: Build and Deploy Code
on: [push, pull_request]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Git Repository
        uses: actions/checkout@v5
      - name: Install Python version 3.9
        uses: actions/setup-python@v6
        with:
          python-version: "3.9"